version: "3.8"

services:
  # Laravel
  app:
    build:
      context: .
      dockerfile: docker/laravel/Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - laravel
    depends_on:
      - mysql
      - redis
    command: >
      bash -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache &&
           chmod -R 775 /var/www/storage /var/www/bootstrap/cache &&
           php-fpm"

  # Nginx para servir o Laravel
  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel
    depends_on:
      - app

  # MySQL
  mysql:
    build:
      context: .
      dockerfile: docker/mysql/Dockerfile
    container_name: laravel_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel

  # Redis
  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: laravel_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
