FROM mysql:8.0

# Variáveis default (serão sobrescritas no docker-compose ou .env)
ENV MYSQL_ROOT_PASSWORD=root
ENV MYSQL_DATABASE=laravel
ENV MYSQL_USER=laravel
ENV MYSQL_PASSWORD=laravel

EXPOSE 3306
